### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by danse** [sic2/awesome-sicily#1]
I would like to work at an English version of this. Ideally i would like to use English as the main language, but if you want we can keep an Italian README and an English README

**Comment by sic2** [comment]
Hi @danse,

That is a great idea! We actually had this in English at first, but then switched to Italian. The reason being that most readers would be Italians. However, we could have a README-EN.md and link that within the main README file. 

@vigliag @giupardeb - ideas?

**Comment by vigliag** [comment]
It could be done (and it would be a very welcomed contribution, thanks!) but I honestly don't see the point.
All the linked pages would be in Italian anyway, and the README is currently a list of names and links, with no descriptions, there's actually not that much to translate. Were you thinking about any specific use-case?

Maintaining both readmes shouldn't be a big deal, at least on our side, but I think it may create some confusion for the people who might want to contribute via pull-requests, as they would have to add things in both lists.

PS: we may also think of keeping a separate ENGLISH.md with information about the list and its purpose and the rules for contributing, while keeping the list itself on the main README.md. I see only pros in doing that (no duplication at all, and the list wasn't going to be translated anyway)

**Comment by danse** [comment]
Well i was chatting today with a guy who is going to visit Eastern Sicily, i wanted to point him to this list but i imagine that the Italian headers and explanations won't be very friendly to him.

I think that in general one has to make a decision about an official language to use in a repo or in an organization, even just on the issues like this one. To be honest i would be curious to find out which communities in Sicily would be able to use English as the official language, i am even thinking about a list of English-friendly communities right now. It might sound funny, but it is the only way to be really accessible to all Europeans and foreigners. Also, for a programmer nowadays not feeling comfortable with English is laughable ... if a community wants to promote the knowledge of programming and increase the cultural exchange in Sicily, that has to go through English i don't see many other ways

**Comment by sic2** [comment]
@danse,
You made a really good point. 

> if a community wants to promote the knowledge of programming and increase the cultural exchange in Sicily, that has to go through English

It will be hard to contact all the communities in that list and check if they are "English-friendly". But it is doable, in principle.

> I think that in general one has to make a decision about an official language to use in a repo or in an organization, even just on the issues like this one. 

Yes, it is hard indeed. We ended up choosing Italian because we thought many users would be Italians. Having this in English is something we could do as @vigliag said above. 
We are using English over here, since you started the issue in English. But do not try using German or French! I cannot help you there :)

**Comment by luca3m** [comment]
We had a similar choice to do within Zencoders a while ago. We organized a ZenConf and we decied to use english as primary language for all the material published on internet. Because in this way our work could get more visibility.

For the same reason I vote for english here. To spread the awesomeness of Sicily more globally :)

BTW, recently on Zencoders we switched to english as main language on our chat room because we added a non-italian speaker and we are happy with it.

**Comment by stefanotorresi** [comment]
I'd go for English only, tbh.

**Comment by danse** [comment]
Well i don't know what you decided guys, but i prepared a pull request. @luca3m is Zencoders still alive? I don't find anybody in the chat on Freenode

**Comment by vigliag** [comment]
I had another approach in mind, checkout the "rendered" branch, tell me what you think :)
You can find a temporary preview (of an incomplete version without any actual link) here
http://vbox.vii.ovh/index_en.html
http://vbox.vii.ovh/index.html
basically there is a list.yaml file that is used to render both html pages. The idea would be updating that list instead of the README.md, then re-rendering the pages with a webhook.
Do you feel it is more complex to handle than a README.md page, or that it would make contributing more difficult? It is certainly more complex to deploy, but I'm okay with it for the time being, I'm more worried about contributions.

**Comment by danse** [comment]
On one side this is a nice idea, it could be deployed with Github pages. On the other hand it makes the list harder to edit for non-coders ... i would say, let's not go overkill: we can keep two lists at the beginning, and see how things go. Maybe both won't grow, maybe one will grow more, or differently from the other, maybe just one will grow and we could abandon the other. If we are all Italians and there are no English-speaking readers or contributors, the problem does not exist

**Comment by luca3m** [comment]
@danse yes we are still alive. We have a Telegram channel here: https://telegram.me/joinchat/CL5_JgWDM96hM1iVhq-EQw
